## Frogwatch Observations

In [1]:
import numpy as np
import pandas as pd

from bokeh.io import output_notebook, show

output_notebook()

### Load data from DB

In [2]:
# import psycopg2 as pg
# db = pg.connect('postgresql://pollard@localhost:5432/frogwatch')

from sqlalchemy import create_engine
engine = create_engine("postgresql+psycopg2://pollard@localhost:5432/frogwatch")

stations = pd.read_sql('select * from stations', engine)
people = pd.read_sql('select * from persons', engine)
observations = pd.read_sql('select * from observations', engine)

#### 1. Normalize species names

In [3]:
sorted(list(observations['species'].unique()))

['Amargosa Toad',
 'American Bullfrog',
 'American Toad',
 'Gray Treefrog',
 'Green Frog',
 'No Species Heard',
 'Pickerel Frog',
 'Southern Leopard Frog',
 'Spring Peeper',
 'Spring Peeper (Subspecies - Northern)',
 'Wood Frog']

In [4]:
import re
observations['species'] = [re.sub(r" \(.*$", "", name) for name in observations['species']]

In [5]:
observations.groupby('species').size().sort_values(ascending=False).keys()

Index(['No Species Heard', 'Spring Peeper', 'American Toad',
       'American Bullfrog', 'Wood Frog', 'Green Frog', 'Gray Treefrog',
       'Pickerel Frog', 'Amargosa Toad', 'Southern Leopard Frog'],
      dtype='str', name='species')

#### 2. Reassign duplicated SMR stations

In [6]:
stations[stations['name'].str.contains('SMR')]

,fs_id,name,lon,lat,city,county,state,owner_id
0,100000220,SMR-Oakdale Overflow Vernal Pool,-74.288740,40.763240,West Orange,Essex County,NJ,100000204
1,100000222,SMR-Orange Reservoir North,-74.283385,40.768369,West Orange,Essex County,NJ,100000204
2,100008954,SMR-Orange Reservoir South,-74.285340,40.759600,West Orange,Essex County,NJ,100000224
3,100000202,SMR-Campbell's Pond,-74.305170,40.737490,Milburn,Essex,NJ,100000108
8,100000218,SMR-Black Willow Pond,-74.292310,40.738760,Maplewood,Essex County,NJ,100000204
9,100000215,SMR-Campbell's Pond,-74.303470,40.737706,Millburn\n,Essex County,NJ,100000204
10,100000221,SMR-High Water Bypass,-74.292300,40.752550,South Orange,Essex County,NJ,100000204
12,100000219,SMR-Elmdale Peace Circle Vernal Pools,-74.304090,40.746560,Miilburn,Essex County,NJ,100000204
13,100000217,SMR-Crest Trail Vernal Pool,-74.290500,40.737440,Maplewood,Essex County,NJ,100000204

In [7]:
smr_station_ids = list([v for v in stations[stations['name'].str.contains('SMR')].fs_id])

In [8]:
len(observations[observations['station_id'].isin(smr_station_ids)])

75

In [9]:
stations[stations['name'].str.contains('South Mountain')]

,fs_id,name,lon,lat,city,county,state,owner_id
5,1480244,South Mountain Reservation Elmdale trail verna...,-74.30466,40.74742,Millburn,Essex,NJ,20074

In [10]:
observations.loc[observations['station_id'] == '593550', 'station_id'] = '100000218'
observations.loc[observations['station_id'] == '1480244', 'station_id'] = '100000219'
observations.loc[observations['station_id'] == '605236', 'station_id'] = '100000215'
observations.loc[observations['station_id'] == '100000202', 'station_id'] = '100000215'
smr_station_ids = [v for v in smr_station_ids if v != '100000202']

In [11]:
len(observations[observations['station_id'].isin(smr_station_ids)])

83

### Denormalize the obervations

In [12]:
obs_and_name = pd.merge(
         observations, 
         people[['fs_id', 'name']], 
         how="left", left_on="observer_id", right_on="fs_id", suffixes=[None, "_observer"])

In [13]:
obs_full = pd.merge(
         obs_and_name, 
         stations[['fs_id', 'name', 'lat', 'lon']], 
         how="left", left_on="station_id", right_on="fs_id", suffixes=[None, "_station"])

In [14]:
obs_full.columns

Index(['fs_id', 'station_id', 'observer_id', 'start_time', 'end_time',
       'species', 'call_intensity', 'temperature', 'beaufort_wind',
       'precip_48h', 'precip', 'above_freezing_48h', 'notes', 'fs_id_observer',
       'name', 'fs_id_station', 'name_station', 'lat', 'lon'],
      dtype='str')

In [15]:
observations = obs_full[['station_id', 'observer_id', 'start_time', 
                         'species', 'call_intensity', 'temperature', 'beaufort_wind', 
                         'name', 'name_station', 'lat', 'lon']]

### Convert start_time to a datetime

In [16]:
observations = observations.assign(
    obs_datetime=pd.to_datetime(observations['start_time'], utc=True))
observations['obs_datetime'].apply(lambda ts: ts.year)

0     2025
1     2025
2     2025
3     2025
4     2025
      ...
94    2025
95    2025
96    2025
97    2025
98    2025
Name: obs_datetime, Length: 99, dtype: int64

### Add week-of-year and month-of-year columns

In [17]:
from datetime import datetime, date
observations['obs_week'] = observations['obs_datetime'].apply(lambda dt: dt.date().isocalendar()[1]) # int 0-52
observations['obs_month'] = observations['obs_datetime'].apply(lambda dt: dt.month) # int 1-12
observations['obs_year_month'] = observations['obs_datetime'].apply(
    lambda dt: datetime(year=dt.year, month=dt.month, day=1)) # date

MONTH = [""] + [date(2000, v, 1).strftime('%b') for v in range(1, 13)]
for dt, obs in observations.groupby(['obs_year_month']).groups.items():
    # print(f"{MONTH[month]}  {len(obs)}")
    print(f"{dt.strftime('%Y-%m')}  {len(obs)}")

2025-02  2
2025-03  25
2025-04  23
2025-05  19
2025-06  10
2025-07  11
2025-08  3
2025-09  3
2025-10  3

/tmp/ipykernel_15220/2376708298.py:8: Pandas4Warning: In a future version, the keys of `groups` will be a tuple with a single element, e.g. (obs_year_month,) , instead of a scalar, e.g. obs_year_month, when grouping by a list with a single element. Use ``df.groupby(by='a').groups`` instead of ``df.groupby(by=['a']).groups`` to avoid this warning
  for dt, obs in observations.groupby(['obs_year_month']).groups.items():

### Extract South Mountain Reservation Observations

In [18]:
smr_observations = observations[observations['station_id'].isin(smr_station_ids) & 
                                (observations['obs_datetime'].apply(lambda ts: ts.year) >= 2010)
                               ].sort_values(by=['obs_datetime'], ascending=False)
smr_observations.loc[:, ('obs_datetime', 'obs_year_month', 'obs_month', 'obs_week',
                         'name', 'species', 'call_intensity', 'temperature', 
                         'beaufort_wind', 'name_station')]

,obs_datetime,obs_year_month,obs_month,obs_week,name,species,call_intensity,temperature,beaufort_wind,name_station
0,2025-10-28 20:21:00+00:00,2025-10-01,10,44,Ed Summers,American Toad,2,50.0,1,SMR-Oakdale Overflow Vernal Pool
8,2025-10-28 19:57:00+00:00,2025-10-01,10,44,Ed Summers,American Toad,1,50.0,2,SMR-Orange Reservoir North
25,2025-10-28 19:22:00+00:00,2025-10-01,10,44,Ed Summers,American Toad,1,50.0,1,SMR-Orange Reservoir South
26,2025-09-18 23:47:00+00:00,2025-09-01,9,38,Ed Summers,American Toad,2,69.0,1,SMR-Orange Reservoir South
9,2025-09-18 23:19:00+00:00,2025-09-01,9,38,Ed Summers,American Toad,2,69.0,1,SMR-Orange Reservoir North
...,...,...,...,...,...,...,...,...,...,...
41,2025-03-10 20:00:00+00:00,2025-03-01,3,11,Alice Hood,No Species Heard,0,59.0,1,SMR-Orange Reservoir South
24,2025-03-10 19:40:00+00:00,2025-03-01,3,11,Alice Hood,No Species Heard,0,59.0,1,SMR-Orange Reservoir North
84,2025-03-09 20:37:00+00:00,2025-03-01,3,10,Tom Pollard,No Species Heard,0,42.0,2,SMR-Black Willow Pond
85,2025-02-28 19:01:00+00:00,2025-02-01,2,9,Tom Pollard,No Species Heard,0,45.0,0,SMR-Black Willow Pond
86,2025-02-26 18:45:00+00:00,2025-02-01,2,9,Tom Pollard,No Species Heard,0,54.0,1,SMR-Black Willow Pond

### Create table of stations

In [19]:
from collections import defaultdict

station_obs = defaultdict(list)

# create an entry for every station in the given observations
for station_id, obs_ids in smr_observations.groupby(['station_id']).groups.items():
    obs = smr_observations.loc[obs_ids[0]]
    station_obs['station_id'].append(station_id)
    station_obs['name'].append(obs["name_station"])
    station_obs['lat'].append(obs['lat'])
    station_obs['lon'].append(obs["lon"])
    station_obs['observations'].append(len(obs_ids))

# Add stations that are defined, but have no observations
for station_id in smr_station_ids:
    if station_id not in station_obs['station_id']:
        station_obs['station_id'].append(station_id)
        station_obs['name'].append(stations.loc[stations['fs_id'] == station_id, "name"].iloc[0])
        station_obs['lat'].append(stations.loc[stations['fs_id'] == station_id, "lat"].iloc[0])
        station_obs['lon'].append(stations.loc[stations['fs_id'] == station_id, "lon"].iloc[0])
        station_obs['observations'].append(0)

station_obs = pd.DataFrame(station_obs)

/tmp/ipykernel_15220/2397126964.py:6: Pandas4Warning: In a future version, the keys of `groups` will be a tuple with a single element, e.g. (station_id,) , instead of a scalar, e.g. station_id, when grouping by a list with a single element. Use ``df.groupby(by='a').groups`` instead of ``df.groupby(by=['a']).groups`` to avoid this warning
  for station_id, obs_ids in smr_observations.groupby(['station_id']).groups.items():

In [20]:
#get_loc('SMR-Orange Reservoir North')
names = ['SMR-Orange Reservoir North', 'SMR-Black Willow Pond']
list(station_obs[station_obs['name'].isin(names)].index)

[2, 6]

### Unified dashboard

* Define sources for different the dashboard panels from the observations and a set of filters.
* Allow filters to be defined by interacting with the panels.

In [21]:
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
from bokeh.models import HoverTool, PanTool, WheelZoomTool, BoxZoomTool, ResetTool, TapTool
from bokeh.models import DataTable, DateFormatter, TableColumn
from bokeh.models import DatetimeTickFormatter
from bokeh.models import Circle, Paragraph
from bokeh.layouts import layout

In [22]:
from bokeh.plotting import gmap
from bokeh.models import GMapOptions

In [23]:
from datetime import datetime
import math

def now():
    return datetime.now().isoformat()

def year_start(dt):
    return dt.replace(month=1, day=1, hour=0, minute=0, second=0)

def year_end(dt):
    return dt.replace(month=12, day=31, hour=0, minute=0, second=0)

MONTH = [""] + [date(2000, v, 1).strftime('%b') for v in range(1, 13)]
MONTH_MILLIS = 30 * 24 * 60 * 60 * 1000

def update_display(doc):

    # Set API key from environment in production:
    api_key = "AIzaSyD4IiUSTkgTTe800sjX5LIuVhUsAFsRqG4"

    all_stations = set(station_obs['name'])
    selected_stations = all_stations
    print(f"{len(selected_stations)} stations")

    all_species = set(smr_observations['species'])
    selected_species = all_species
    print(f"{len(selected_species)} species")

    all_observers = set(smr_observations['name'])
    selected_observers = all_observers
    print(f"{len(selected_observers)} observers")
    
    print(f"{len(smr_observations)} total observations")
    
    min_obs_time = year_start(min(smr_observations['obs_datetime']))
    max_obs_time = year_end(max(smr_observations['obs_datetime']))
    max_year_month_count = max(smr_observations.groupby('obs_year_month').size())
    max_week_count = max(smr_observations.groupby('obs_week').size())
    max_month_count = max(smr_observations.groupby('obs_month').size())
    
    full_date_range = [min_obs_time, max_obs_time]
    selected_date_range = list(full_date_range)
    
    # If updating is true, we're in the middle of a data source update, 
    # and the usual selection callbacks should be suppressed.
    updating = False
    
    def something_changed(attrname, old, new):
        print(attrname + " " + repr(old))

    def print_selections():
        print(f"stations: {station_source.selected.indices}  ({len(selected_stations)} selected_stations)")
        print(f"species: {species_table.source.selected.indices}  ({len(selected_species)} selected_species)")
        print(f"people: {people_table.source.selected.indices}  ({len(selected_observers)} selected_observers)")
        print(f"obs: {obs_table.source.selected.indices}")
        
    def obs_selected(attrname, old, new):
        print(f"{now()} - obs_selected()")
        print(f"observations {obs_table.source.selected.indices} selected")
         
    def date_range_selected(attrname, old, new):
        print(f"{now()} - date_range_selected()")
        print(f"date_range {obs_date_histogram.x_range} selected")
       
    def stations_selected(attrname, old, new):
        nonlocal selected_stations
        if not updating:
            print(f"{now()} - stations_selected()")
            selected_stations = list(
                station_obs['name'][station_source.selected.indices]
            ) or all_stations
            print(f"Selected stations {', '.join(selected_stations)}")
            update_panels()
        
    def species_selected(attrname, old, new):
        nonlocal selected_species
        if not updating:
            try:
                print(f"{now()} - species_selected()")
                selection = species_table.source.selected.indices
                selected_species = [
                    species_table.source.data['species'][idx] for idx in selection
                ] or all_species
            except IndexError:
                selected_species = all_species
            print(f"Selected species {', '.join(selected_species)}")
            update_panels()
        
    def observer_selected(attrname, old, new):
        nonlocal selected_observers
        if not updating:
            print(f"{now()} - observer selected")
            try:
                selection = people_table.source.selected.indices
                selected_observers = [
                    people_table.source.data['name'][idx] for idx in selection
                ] or all_observers
            except IndexError:
                selected_observers = all_observers
            # print(f"Selected observers {', '.join(selected_observers)}")
            update_panels()
        
    def select_stations_by_name(stations):
        station_source.selected.indices = list(
            station_obs[station_obs['name'].isin(stations)].index
        )
        print(f"set station indices to {station_source.selected.indices}")
    
    def unselect_stations():
        station_source.selected.indices = []
        print(f"reset station indices to {station_source.selected.indices}")

    def update_panels():
        nonlocal updating
        if not updating:
            updating = True
            print_selections()
            station_filter = smr_observations['name_station'].isin(selected_stations)
            species_filter = smr_observations['species'].isin(selected_species)
            observer_filter = smr_observations['name'].isin(selected_observers)
            filtered_observations = smr_observations[
                station_filter & species_filter & observer_filter
            ]
            print(f"{len(filtered_observations)} filtered observations")
        
            # if observations have been filtered,
            # select the stations where the observations were made.
            if len(filtered_observations) == len(smr_observations):
                unselect_stations()
            elif len(selected_stations) == len(all_stations):
                select_stations_by_name(filtered_observations['name_station'].unique())
        
            obs_table.source = obs_source(filtered_observations)
            species_table.source=species_source(filtered_observations)
            people_table.source=people_source(filtered_observations)

            obs_date_histogram.renderers[0].data_source.data = dict(obs_time_source(filtered_observations).data)
            obs_date_histogram.y_range.end = 1.1 * max(obs_date_histogram.renderers[0].data_source.data['count'])

            obs_month_histogram.renderers[0].data_source.data = dict(obs_month_source(filtered_observations).data)
            obs_month_histogram.y_range.end = 1.1 * max(obs_month_histogram.renderers[0].data_source.data['count'])
            
            updating = False

    # There may be stations that have no observations, so we can'td efine this source 
    # just from the observations.
    station_source = ColumnDataSource(
        data=dict(
            lat=station_obs['lat'],
            lon=station_obs['lon'],
            name=station_obs['name'],
            count=station_obs['observations'],
            size=[12 + 5*math.log(v + 1) for v in station_obs['observations']],
        )
    )

    station_source.selected.on_change('indices', stations_selected)
        
    def obs_source(observations):
        column_source = ColumnDataSource(
            data=dict(
                obs_datetime=observations['obs_datetime'],
                station=observations['name_station'],
                observer=observations['name'],
                species=observations['species'],
                intensity=observations['call_intensity'],
                temperature=observations['temperature'],
                wind=observations['beaufort_wind'],
            )
        )
        column_source.selected.on_change('indices', obs_selected)
        return column_source

    def species_source(observations):
        by_species = observations[observations['species'] != 'No Species Heard'].groupby('species')
        names = list(by_species.size().sort_values(ascending=False).keys())
        groups = dict(list(by_species))
        
        count, observers, sites = list(), list(), list()
        for species in names:
            group = groups[species]
            count.append(len(group))
            observers.append(len(group['name'].unique()))
            sites.append(len(group['name_station'].unique()))
        column_source = ColumnDataSource(
            data=dict(
                species=names,
                observations=count,
                observers=observers,
                stations=sites
            )
        )
        column_source.selected.on_change('indices', species_selected)
        return column_source

    def unique_species(species_list):
        """Return a list of the unique species in the given list."""
        species = set([v for v in species_list if v != "No Species Heard"])
        return sorted(list(species))
        
    def people_source(observations):
        by_observer = observations.groupby('name')
        names = list(by_observer.size().sort_values(ascending=False).keys())
        groups = dict(list(by_observer))
        
        count, species, sites = list(), list(), list()
        for observer in names:
            group = groups[observer]
            count.append(len(group))
            species.append(len(unique_species(group['species'])))
            sites.append(len(group['name_station'].unique()))
        column_source = ColumnDataSource(
            data=dict(
                name=names,
                observations=count,
                species=species,
                stations=sites
            )
        )
        column_source.selected.on_change('indices', observer_selected)
        return column_source
         
    def obs_time_source(observations):
        by_year_month = observations.groupby('obs_year_month')
        months = list(by_year_month.groups.keys())
        column_source = ColumnDataSource(
            data=dict(
                obs_year_month=months,
                date=[v.strftime('%b %Y') for v in months],
                count=list(by_year_month.size().values)
            )
        )
        # print(column_source.__dict__)
        return column_source
         
    def obs_month_source(observations):
        by_month = {month: 0 for month in range(1,13)}
        for month, obs in observations.groupby('obs_month'):
            by_month[month] = len(obs)
        column_source = ColumnDataSource(
            data=dict(
                obs_month=list(by_month.keys()),
                month=[MONTH[v] for v in by_month.keys()],
                count=list(by_month.values())
            )
        )
        return column_source

    # Date histogram    
    date_hover = HoverTool(tooltips=[
        ("month", "@date"),
        ("obs", "@count"),
    ])
    date_zoom = BoxZoomTool(dimensions="width")

    obs_date_histogram = figure(x_range=(min_obs_time, max_obs_time), y_range=(0, max_year_month_count*1.1), 
                      width=810, height=160, x_axis_type="datetime", 
                      tools=[date_hover, date_zoom, PanTool(dimensions="width"), ResetTool()],
                      active_drag=date_zoom,
                      title="Observations by Year and Month")
    obs_date_histogram.vbar(x='obs_year_month', top='count', bottom=0, width=MONTH_MILLIS * 0.8, 
                  source=obs_time_source(smr_observations))
    obs_date_histogram.xaxis[0].formatter = DatetimeTickFormatter(months="%b %Y")


    # Month histogram    
    month_hover = HoverTool(tooltips=[
        ("month", "@month"),
        ("obs", "@count"),
    ])

    obs_month_histogram = figure(x_range=(1, 12), y_range=(0, max_month_count*1.1), 
                      width=810, height=160, 
                      tools=[month_hover],
                      title="Observations by Month")
    obs_month_histogram.vbar(x='obs_month', top='count', bottom=0, width=0.8, 
                  source=obs_month_source(smr_observations))
    obs_date_histogram.xaxis[0].formatter = DatetimeTickFormatter(months="%b %Y")
    # print(obs_date_histogram.y_range)

    # Station map
    map_options = GMapOptions(lat=40.752, lng=-74.294, map_type="terrain", zoom=14)

    site_hover = HoverTool(tooltips=[
        ("site", "@name"),
    ])

    station_map = gmap(api_key, map_options,
                       tools=[site_hover, WheelZoomTool(), PanTool(), ResetTool(), TapTool()],
                       width=400,
                       title="South Mountain Reservation")

    renderer = station_map.circle(x="lon", y="lat", size="size", 
                       fill_color="violet", fill_alpha=0.5,
                       hover_fill_alpha=1.0,
                       source=station_source)
    
    selected_circle = Circle(fill_alpha=1.0, fill_color="violet")
    nonselected_circle = Circle(fill_alpha=0.0, fill_color="violet")

    renderer.selection_glyph = selected_circle
    renderer.nonselection_glyph = nonselected_circle

    # Observations table
    obs_columns = [
        TableColumn(field="obs_datetime", title="Observed at", formatter=DateFormatter()),
        TableColumn(field="station", title="Station"),
        TableColumn(field="observer", title="Observer"),
        TableColumn(field="species", title="Species"),
        TableColumn(field="intensity", title="Intensity"),
    ]

    obs_table = DataTable(source=obs_source(smr_observations), columns=obs_columns, 
                          width=810, height=320, index_position=None)
    # Species table
    species_columns = [
        TableColumn(field="species", title="Species"),
        TableColumn(field="observations", title="Observed"),
        TableColumn(field="observers", title="Observers"),
        TableColumn(field="stations", title="Sites"),
    ]

    species_table = DataTable(source=species_source(smr_observations), 
                              columns=species_columns, 
                              width=400, height=240, margin=(30, 5, 5, 5), 
                              index_position=None)
    # Observers table
    people_columns = [
        TableColumn(field="name", title="Observer"),
        TableColumn(field="observations", title="Observed"),
        TableColumn(field="species", title="Species"),
        TableColumn(field="stations", title="Sites"),
    ]

    people_table = DataTable(source=people_source(smr_observations), 
                              columns=people_columns, 
                              width=400, height=240, margin=(30, 5, 5, 5), 
                              index_position=None)
    status = Paragraph()
    
    def source_properties():
        lines = list()
        lines.append("obs_source:")
        for k, v in obs_source.properties_with_values().items():
            lines.append(f"{k:10s}: {str(v)[:64]}")
        lines.append("")
        lines.append("station_source:")
        for k, v in station_source.properties_with_values().items():
            lines.append(f"{k:10s}: {str(v)[:64]}")
        return "\n".join(lines)
    
    def selections():
        lines = list()
        lines.append(f"observations: {str(obs_table.source.selected.indices)}")
        lines.append(f"stations: {str(station_source.selected.indices)}")
        return "\t\t".join(lines)
    
    # status.text = "all observations"
    # print(status.text)

    doc.add_root(layout(
        [[station_map, [species_table, people_table]], [obs_date_histogram], [obs_month_histogram], [obs_table]])
    )
    
# In the notebook, just pass the function that defines the app to show
# You may need to supply notebook_url, e.g notebook_url="http://localhost:8889" 
show(update_display)

8 stations
9 species
10 observers
83 total observations

BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
ERROR:tornado.application:Uncaught exception GET /autoload.js?bokeh-autoload-element=e63dc925-2470-457a-8c1a-c38ea43f2562&bokeh-absolute-url=http://localhost:38373&resources=none (::1)
HTTPServerRequest(protocol='http', host='localhost:38373', method='GET', uri='/autoload.js?bokeh-autoload-element=e63dc925-2470-457a-8c1a-c38ea43f2562&bokeh-absolute-url=http://localhost:38373&resources=none', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/tornado/web.py", line 1859, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/server/views/autoload_js_handler.py", line 68, in get
    session = await self.get_session()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/server/views/session_handler.py", line 145, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/server/contexts.py", line 240, in create_session_if_needed
    self._application.initialize_document(doc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/application/application.py", line 190, in initialize_document
    h.modify_document(doc)
    ~~~~~~~~~~~~~~~~~^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/application/handlers/function.py", line 140, in modify_document
    self._func(doc)
    ~~~~~~~~~~^^^^^
  File "/tmp/ipykernel_15220/3522249831.py", line 361, in update_display
    doc.add_root(layout(
    ~~~~~~~~~~~~^^^^^^^^
        [[station_map, [species_table, people_table]], [obs_date_histogram], [obs_month_histogram], [obs_table]])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/document/document.py", line 331, in add_root
    with self.models.freeze():
         ~~~~~~~~~~~~~~~~~~^^
  File "/home/pollard/.local/share/uv/python/cpython-3.13.5-linux-x86_64-gnu/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/document/models.py", line 135, in freeze
    self._pop_freeze()
    ~~~~~~~~~~~~~~~~^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/document/models.py", line 288, in _pop_freeze
    self.recompute()
    ~~~~~~~~~~~~~~^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/document/models.py", line 215, in recompute
    new_models |= mr.references()
                  ~~~~~~~~~~~~~^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/model/model.py", line 492, in references
    return set(collect_models(self))
               ~~~~~~~~~~~~~~^^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/model/util.py", line 139, in collect_models
    return collect_filtered_models(None, *input_values)
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/model/util.py", line 119, in collect_filtered_models
    visit_immediate_value_references(obj, queue_one)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/model/util.py", line 185, in visit_immediate_value_references
    child = getattr(value, attr)
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/core/property/descriptors.py", line 282, in __get__
    raise UnsetValueError(f"{obj}.{self.name} doesn't have a value set")
bokeh.core.property.descriptors.UnsetValueError: Circle(id='p1151', ...).radius doesn't have a value set
ERROR:tornado.application:Uncaught exception GET /autoload.js?bokeh-autoload-element=e63dc925-2470-457a-8c1a-c38ea43f2562&bokeh-absolute-url=http://localhost:38373&resources=none (::1)
HTTPServerRequest(protocol='http', host='localhost:38373', method='GET', uri='/autoload.js?bokeh-autoload-element=e63dc925-2470-457a-8c1a-c38ea43f2562&bokeh-absolute-url=http://localhost:38373&resources=none', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/tornado/web.py", line 1859, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/server/views/autoload_js_handler.py", line 68, in get
    session = await self.get_session()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/server/views/session_handler.py", line 145, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/server/contexts.py", line 240, in create_session_if_needed
    self._application.initialize_document(doc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/application/application.py", line 190, in initialize_document
    h.modify_document(doc)
    ~~~~~~~~~~~~~~~~~^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/application/handlers/function.py", line 140, in modify_document
    self._func(doc)
    ~~~~~~~~~~^^^^^
  File "/tmp/ipykernel_15220/3522249831.py", line 361, in update_display
    doc.add_root(layout(
    ~~~~~~~~~~~~^^^^^^^^
        [[station_map, [species_table, people_table]], [obs_date_histogram], [obs_month_histogram], [obs_table]])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/document/document.py", line 331, in add_root
    with self.models.freeze():
         ~~~~~~~~~~~~~~~~~~^^
  File "/home/pollard/.local/share/uv/python/cpython-3.13.5-linux-x86_64-gnu/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/document/models.py", line 135, in freeze
    self._pop_freeze()
    ~~~~~~~~~~~~~~~~^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/document/models.py", line 288, in _pop_freeze
    self.recompute()
    ~~~~~~~~~~~~~~^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/pythonERROR:tornado.access:500 GET /autoload.js?bokeh-autoload-element=e63dc925-2470-457a-8c1a-c38ea43f2562&bokeh-absolute-url=http://localhost:38373&resources=none (::1) 334.94ms
3.13/site-packages/bokeh/document/models.py", line 215, in recompute
    new_models |= mr.references()
                  ~~~~~~~~~~~~~^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/model/model.py", line 492, in references
    return set(collect_models(self))
               ~~~~~~~~~~~~~~^^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/model/util.py", line 139, in collect_models
    return collect_filtered_models(None, *input_values)
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/model/util.py", line 119, in collect_filtered_models
    visit_immediate_value_references(obj, queue_one)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/model/util.py", line 185, in visit_immediate_value_references
    child = getattr(value, attr)
  File "/home/pollard/frogwatch-stuff/frogwatch/.venv/lib/python3.13/site-packages/bokeh/core/property/descriptors.py", line 282, in __get__
    raise UnsetValueError(f"{obj}.{self.name} doesn't have a value set")
bokeh.core.property.descriptors.UnsetValueError: Circle(id='p1151', ...).radius doesn't have a value set
ERROR:tornado.access:500 GET /autoload.js?bokeh-autoload-element=e63dc925-2470-457a-8c1a-c38ea43f2562&bokeh-absolute-url=http://localhost:38373&resources=none (::1) 334.94ms