## Frogwatch Observations

In [1]:
import numpy as np
import pandas as pd

from bokeh.io import output_notebook, show

output_notebook()

In [ ]:
"""
import psycopg2 as pg
db = pg.connect('postgresql://pollard@localhost:5432/frogwatch')

stations = pd.read_sql('select * from stations', db)
people = pd.read_sql('select * from persons', db)
observations = pd.read_sql('select * from observations', db)
"""

In [2]:
import sqlite3
db = sqlite3.connect('frogwatch.db')

stations = pd.read_sql('select * from stations', db)
people = pd.read_sql('select * from persons', db)
observations = pd.read_sql('select * from observations', db)

In [3]:
observations['fs_id'] = observations['fs_id'].apply(pd.to_numeric);
stations['fs_id'] = stations['fs_id'].apply(pd.to_numeric);
people['fs_id'] = people['fs_id'].apply(pd.to_numeric);

In [4]:
stations

,fs_id,name,lon,lat,city,county,state,owner_id
0,100000218,SMR-Black Willow Pond,-74.292310,40.738760,Maplewood,Essex County,NJ,100000204
1,100048348,Colombia Trail,-74.525440,40.753130,califon,None,NJ,23996
2,100049378,Kay Center,-74.709270,40.806928,Chester,Morris,NJ,23996
3,3039964,Great Swamp National Wildlife Refuge,-74.503208,40.709260,None,Morris County,NJ,23996
4,3277109,Briant Park,-74.333180,40.715539,Summit,Union,NJ,23996
...,...,...,...,...,...,...,...,...
7079,2237033,Home,-72.456007,41.683239,Marlborough,Hartford,CT,24759
7080,2237034,Home,-72.456007,41.683239,Marlborough,Hartford,CT,24759
7081,2237049,Union Stream,-91.021400,38.402900,Union,Franklin,MO,24653
7082,2237787,Fountain Hill,-72.432367,41.385786,Deep River,USA,CT,24778
7083,2237788,cabin pond,-93.509917,35.907747,None,Newton,AR,19859

In [5]:
observations.head()

,fs_id,station_id,observer_id,start_time,end_time,species,call_intensity,temperature,beaufort_wind,precip_48h,precip,above_freezing_48h,notes
0,100753727,100000218,100000108,2023-02-13 18:15:00,2023-02-13 18:45:00,No Species Heard,0,50.0,2,2,0,1,None
1,100753386,100000218,100000108,2023-02-10 07:30:00,None,No Species Heard,0,51.0,1,2,0,1,None
2,100726555,100000218,100000204,2022-07-14 21:15:00,2022-07-14 21:18:00,No Species Heard,0,84.0,1,1,0,1,site was dry
3,100728190,100000218,100000265,2022-07-12 21:24:00,2022-07-12 21:27:00,No Species Heard,0,80.0,1,1,0,1,None
4,100726556,100000218,100000204,2022-06-09 21:20:00,2022-06-09 21:23:00,Green Frog,1,67.0,1,3,0,1,None

#### 1. Normalize species names

In [6]:
sorted(list(observations['species'].unique()))

['Amargosa Toad',
 'American Bullfrog',
 'American Toad',
 'Atlantic Coast Leopard Frog',
 'Carpenter Frog',
 "Cope's Gray Treefrog",
 'Eastern Cricket Frog',
 'Eastern Spadefoot',
 "Fowler's Toad",
 'Gray Treefrog',
 'Green Frog',
 'Green Frog (Subspecies - Northern)',
 'New Jersey Chorus Frog',
 'No Species Heard',
 'Northern Cricket Frog Complex',
 'Pickerel Frog',
 'Pine Barrens Treefrog',
 'Southern Leopard Frog',
 'Spring Peeper',
 'Spring Peeper (Subspecies - Northern)',
 'Upland Chorus Frog',
 'Wood Frog']

In [7]:
import re
observations['species'] = [re.sub(r" \(.*$", "", name) for name in observations['species']]

In [8]:
by_species = observations.groupby('species')
by_species.size().sort_values(ascending=False).keys()

Index(['No Species Heard', 'Spring Peeper', 'Green Frog', 'American Bullfrog',
       'Gray Treefrog', 'Fowler's Toad', 'Wood Frog',
       'Northern Cricket Frog Complex', 'Cope's Gray Treefrog',
       'Pine Barrens Treefrog', 'Southern Leopard Frog',
       'New Jersey Chorus Frog', 'Atlantic Coast Leopard Frog',
       'Pickerel Frog', 'American Toad', 'Carpenter Frog',
       'Eastern Cricket Frog', 'Amargosa Toad', 'Eastern Spadefoot',
       'Upland Chorus Frog'],
      dtype='object', name='species')

#### 2. Reassign duplicated SMR stations

In [9]:
stations[stations['name'].str.contains('SMR')]

,fs_id,name,lon,lat,city,county,state,owner_id
0,100000218,SMR-Black Willow Pond,-74.292310,40.738760,Maplewood,Essex County,NJ,100000204
5,100000219,SMR-Elmdale Peace Circle Vernal Pools,-74.304090,40.746560,Miilburn,Essex County,NJ,100000204
6,100000221,SMR-High Water Bypass,-74.292300,40.752550,South Orange,Essex County,NJ,100000204
7,100008954,SMR-Orange Reservoir South,-74.285340,40.759600,West Orange,Essex County,NJ,100000224
8,100000222,SMR-Orange Reservoir North,-74.283385,40.768369,West Orange,Essex County,NJ,100000204
9,100000215,SMR-Campbell's Pond,-74.303470,40.737706,Millburn\n,Essex County,NJ,100000204
12,100000202,SMR-Campbell's Pond,-74.305170,40.737490,Milburn,Essex,NJ,100000108
13,100000217,SMR-Crest Trail Vernal Pool,-74.290500,40.737440,Maplewood,Essex County,NJ,100000204
14,100000220,SMR-Oakdale Overflow Vernal Pool,-74.288740,40.763240,West Orange,Essex County,NJ,100000204

In [10]:
smr_station_ids = list([int(v) for v in stations[stations['name'].str.contains('SMR')].fs_id])

In [11]:
len(observations[observations['station_id'].isin(smr_station_ids)])

0

In [12]:
stations[stations['name'].str.contains('South Mountain')]

,fs_id,name,lon,lat,city,county,state,owner_id
10,605236,"Campbell's Pond, South Mountain Reservation",-74.303005,40.738104,Maplewood,Essex,NJ,20074
11,4975303,South Mountain Reservation-Elmdale/Peace Circle,-74.297222,40.746944,Short Hills,Essex,NJ,28679
26,593550,"Crest Drive Deer exclosure, South Mountain Res...",-74.292201,40.738704,Maplewood,Essex,NJ,20074
5203,1480244,South Mountain Reservation Elmdale trail verna...,-74.304660,40.747420,Millburn,Essex,NJ,20074

In [13]:
observations.loc[observations['station_id'] == 593550, 'station_id'] = 100000218
observations.loc[observations['station_id'] == 1480244, 'station_id'] = 100000219
observations.loc[observations['station_id'] == 605236, 'station_id'] = 100000215
observations.loc[observations['station_id'] == 100000202, 'station_id'] = 100000215
smr_station_ids = [v for v in smr_station_ids if v != 100000202]

In [14]:
len(observations[observations['station_id'].isin(smr_station_ids)])

0

### Denormalize the obervations

In [ ]:
obs_and_name = pd.merge(
         observations, 
         people[['fs_id', 'name']], 
         how="left", left_on="observer_id", right_on="fs_id", suffixes=[None, "_observer"])

In [ ]:
obs_full = pd.merge(
         obs_and_name, 
         stations[['fs_id', 'name', 'lat', 'lon']], 
         how="left", left_on="station_id", right_on="fs_id", suffixes=["_observer", "_station"])

In [ ]:
obs_full.columns

In [ ]:
observations = obs_full[['station_id', 'observer_id', 'start_time', 
                         'species', 'call_intensity', 'temperature', 'beaufort_wind', 
                         'name_observer', 'name_station', 'lat', 'lon']]

In [ ]:
### Make start_time a datetime

In [ ]:
type(pd.to_datetime(observations['start_time'], utc=True))

In [ ]:
pd.Timestamp('2015-04-03 23:45:04').year
observations = observations.assign(
    start_time=pd.to_datetime(observations['start_time'], utc=True))
observations['start_time'].apply(lambda ts: ts.year)

In [ ]:
### Add week-of-year and month-of-year columns

In [ ]:
from datetime import datetime, date
observations['obs_week'] = observations['obs_datetime'].apply(lambda dt: dt.date().isocalendar()[1]) # int 0-52
observations['obs_month'] = observations['obs_datetime'].apply(lambda dt: dt.month) # int 1-12
observations['obs_year_month'] = observations['obs_datetime'].apply(
    lambda dt: datetime(year=dt.year, month=dt.month, day=1)) # date

MONTH = [""] + [date(2000, v, 1).strftime('%b') for v in range(1, 13)]
for dt, obs in observations.groupby(['obs_year_month']).groups.items():
    # print(f"{MONTH[month]}  {len(obs)}")
    print(f"{dt.strftime('%Y-%m')}  {len(obs)}")

In [ ]:
smr_observations = observations[observations['station_id'].isin(smr_station_ids) & 
                                (observations['start_time'].apply(lambda ts: ts.year) >= 2010)
                               ].sort_values(by=['start_time'], ascending=False)
smr_observations.loc[:, ('start_time', 'name_observer', 'species', 'call_intensity', 'temperature', 'beaufort_wind', 'name_station')]

In [ ]:
smr_observations.groupby('name_station').size()

In [ ]:
smr_observations.groupby('species')['name_station'].unique()

In [ ]:
names = list()
species_obs = list()
for species, group in smr_observations.groupby('species'):
    names.append(species)
    species_obs.append({
        "observations": len(group),
        "observers": len(group['name_observer'].unique()),
        "sites": len(group['name_station'].unique()),
    })
pd.DataFrame(species_obs, index=names).sort_values('observations', ascending=False)

In [ ]:
smr_observations.groupby('name_observer').size().sort_values(ascending=False)

In [ ]:
stations.loc[stations['fs_id'] == 100000219, 'name'].iloc[0]

In [ ]:
from collections import defaultdict

station_obs = defaultdict(list)

# create an entry for every station in the given observations
for station_id, obs_ids in smr_observations.groupby(['station_id']).groups.items():
    obs = smr_observations.loc[obs_ids[0]]
    station_obs['station_id'].append(station_id)
    station_obs['name'].append(obs["name_station"])
    station_obs['lat'].append(obs['lat'])
    station_obs['lon'].append(obs["lon"])
    station_obs['observations'].append(len(obs_ids))
    
    species = set([smr_observations.loc[obs_id]['species'] for obs_id in obs_ids])
    station_obs["species"].append(sorted(list([v for v in species if v != "No Species Heard"])))

# Add stations that are defined, but have no observations
for station_id in smr_station_ids:
    if station_id not in station_obs['station_id']:
        station_obs['station_id'].append(station_id)
        station_obs['name'].append(stations.loc[stations['fs_id'] == station_id, "name"].iloc[0])
        station_obs['lat'].append(stations.loc[stations['fs_id'] == station_id, "lat"].iloc[0])
        station_obs['lon'].append(stations.loc[stations['fs_id'] == station_id, "lon"].iloc[0])
        station_obs['observations'].append(0)
        station_obs["species"].append([])

station_obs = pd.DataFrame(station_obs)
station_obs

### Map the observations

#### Google Maps Plots

In [ ]:
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
from bokeh.models import HoverTool, PanTool, WheelZoomTool, ResetTool, TapTool
from bokeh.models import DataTable, DateFormatter, TableColumn
from bokeh.layouts import layout

In [ ]:
from bokeh.models import GMapOptions, Paragraph
from bokeh.plotting import gmap

In [ ]:
import math

map_options = GMapOptions(lat=40.752, lng=-74.294, map_type="terrain", zoom=14)

# Set API key from environment in production:
api_key = "AIzaSyD4IiUSTkgTTe800sjX5LIuVhUsAFsRqG4"

# There may be stations that have no observations, so we define this source independently of the observations
station_source = ColumnDataSource(
    data = dict(
        lat=list(station_obs['lat']),
        lon=list(station_obs['lon']),
        name=list(station_obs['name']),
        count=list(station_obs['observations']),
        species=list(station_obs['species']),
        size=[10 + 7*math.log(v + 1) for v in station_obs['observations']],

    )
)

hover = HoverTool(tooltips=[
    ("site", "@name"),
    ("observations", "@count"),
    ("species", "@species")
])

station_map = gmap(api_key, map_options,
                   tools=[hover, WheelZoomTool(), PanTool(), ResetTool(), TapTool()],
                   title="South Mountain Reservation",
                   width_policy="max")

station_map.circle(x="lon", y="lat", size="size", fill_color="violet", fill_alpha=0.8, 
                   source=station_source)
show(station_map)

In [ ]:
smr_observations.head()

In [ ]:
selected_stations = [] # ['SMR-Black Willow Pond']
if selected_stations:
    station_filter = smr_observations['name_station'].isin(selected_stations)
else:
    station_filter = smr_observations['name_station'].notnull()
    
selected_species = ['Wood Frog']
if selected_species:
    species_filter = smr_observations['species'].isin(selected_species)
else:
    species_filter = smr_observations['species'].notnull()
    
# smr_observations[station_filter and species_filter]
smr_observations[species_filter & station_filter]

### Unified dashboard

* Define sources for different the dashboard panels from the observations and a set of filters.
* Allow filters to be defined by interacting with the panels.

In [ ]:
from bokeh.models import Circle
from datetime import datetime

def now():
    return datetime.now().isoformat()

def update_display(doc):

    # Set API key from environment in production:
    api_key = "AIzaSyD4IiUSTkgTTe800sjX5LIuVhUsAFsRqG4"

    all_stations = set(station_obs['name'])
    selected_stations = all_stations
    print(f"{len(selected_stations)} stations")

    all_species = set(smr_observations['species'])
    selected_species = all_species
    print(f"{len(selected_species)} species")
    
    def something_changed(attrname, old, new):
        status.text = attrname + " " + repr(old)

    def obs_selected(attrname, old, new):
        print(f"{now()} - observation selected")
        status.text = f"observations {obs_table.source.selected.indices} selected"
        
    def stations_selected(attrname, old, new):
        print(f"{now()} - station selected")
        nonlocal selected_stations
        selected_stations = list(station_obs['name'][station_source.selected.indices]) or all_stations
        status.text = f"Selected stations {', '.join(selected_stations)}"
        species_selected = all_species
        update_panels()
        
    def species_selected(attrname, old, new):
        print(f"{now()} - species selected")
        nonlocal selected_species
        try:
            selected_species = [
                species_table.source.data['species'][idx] for idx in species_table.source.selected.indices
            ] or all_species
        except IndexError:
            selected_species = all_species
        status.text = f"Selected species {', '.join(selected_species)}"
        update_panels()
        
    def update_panels():
        station_filter = smr_observations['name_station'].isin(selected_stations)
        species_filter = smr_observations['species'].isin(selected_species)
        filtered_observations = smr_observations[station_filter & species_filter]
        print(f"{len(filtered_observations)} filtered observations")
        obs_table.source = obs_source(filtered_observations)
        species_table.source=species_source(filtered_observations)

    # There may be stations that have no observations, so we define this source independently of the observations
    station_source = ColumnDataSource(
        data=dict(
            lat=station_obs['lat'],
            lon=station_obs['lon'],
            name=station_obs['name'],
            count=station_obs['observations'],
            species=station_obs['species'],
            size=[10 + 7*math.log(v + 1) for v in station_obs['observations']],
        )
    )

    station_source.selected.on_change('indices', stations_selected)
        
    def obs_source(observations):
        column_source = ColumnDataSource(
            data=dict(
                obs_time=observations['start_time'],
                station=observations['name_station'],
                observer=observations['name_observer'],
                species=observations['species'],
                intensity=observations['call_intensity'],
                temperature=observations['temperature'],
                wind=observations['beaufort_wind'],
            )
        )
        column_source.selected.on_change('indices', obs_selected)
        return column_source

    def species_source(observations):
        by_species = observations.groupby('species')
        names = list(by_species.size().sort_values(ascending=False).keys())
        groups = dict(list(by_species))
        
        count, observers, sites = list(), list(), list()
        for species in names:
            group = groups[species]
            count.append(len(group))
            observers.append(len(group['name_observer'].unique()))
            sites.append(len(group['name_station'].unique()))
        column_source = ColumnDataSource(
            data=dict(
                species=names,
                observations=count,
                observers=observers,
                stations=sites
            )
        )
        column_source.selected.on_change('indices', species_selected)
        return column_source
    
    # Station map
    map_options = GMapOptions(lat=40.752, lng=-74.294, map_type="terrain", zoom=14)

    hover = HoverTool(tooltips=[
        ("site", "@name"),
    ])

    station_map = gmap(api_key, map_options,
                       tools=[hover, WheelZoomTool(), PanTool(), ResetTool(), TapTool()],
                       width=600,
                       title="South Mountain Reservation")

    renderer = station_map.circle(x="lon", y="lat", size="size", 
                       fill_color="violet", fill_alpha=0.5,
                       hover_fill_alpha=1.0,
                       source=station_source)
    
    selected_circle = Circle(fill_alpha=1.0, fill_color="violet")
    nonselected_circle = Circle(fill_alpha=0.0, fill_color="violet")

    renderer.selection_glyph = selected_circle
    renderer.nonselection_glyph = nonselected_circle

    # Observations table
    obs_columns = [
        TableColumn(field="obs_time", title="Observed at", formatter=DateFormatter()),
        TableColumn(field="station", title="Station"),
        TableColumn(field="observer", title="Observer"),
        TableColumn(field="species", title="Species"),
        TableColumn(field="intensity", title="Intensity"),
    ]

    obs_table = DataTable(source=obs_source(smr_observations), columns=obs_columns, 
                          width=900, height=280, index_position=None, autosize_mode="fit_viewport")
    # Species table
    species_columns = [
        TableColumn(field="species", title="Species"),
        TableColumn(field="observations", title="Observed"),
        TableColumn(field="observers", title="Observers"),
        TableColumn(field="stations", title="Sites"),
    ]

    species_table = DataTable(source=species_source(smr_observations), columns=species_columns, 
                              width=900, height=280, margin=(30, 5, 5, 5), index_position=None,
                              autosize_mode="fit_viewport")
   
    status = Paragraph()
    
    def source_properties():
        lines = list()
        lines.append("obs_source:")
        for k, v in obs_source.properties_with_values().items():
            lines.append(f"{k:10s}: {str(v)[:64]}")
        lines.append("")
        lines.append("station_source:")
        for k, v in station_source.properties_with_values().items():
            lines.append(f"{k:10s}: {str(v)[:64]}")
        return "\n".join(lines)
    
    def selections():
        lines = list()
        lines.append(f"observations: {str(obs_table.source.selected.indices)}")
        lines.append(f"stations: {str(station_source.selected.indices)}")
        return "\t\t".join(lines)
    
    status.text = "all observations"
    print(status.text)

    doc.add_root(layout([[station_map, species_table], [status], [obs_table]]))
    
# In the notebook, just pass the function that defines the app to show
# You may need to supply notebook_url, e.g notebook_url="http://localhost:8889" 
show(update_display)

#### WMTS Plots

In [ ]:
from bokeh.plotting import figure
from bokeh.models import WMTSTileSource
from bokeh.tile_providers import get_provider, OSM

In [ ]:
import math

def lonlat_to_web_mercator(lon=None, lat=None):
    """Converts lists of decimal longitude and latitude values to web mercator x and y values."""
    k = 6378137
    x = [v * (k * math.pi/180.0) for v in lon] if lon else []
    y = [math.log(math.tan((90.0 + v) * np.pi/360.0)) * k for v in lat] if lat else []
    return x, y

In [ ]:
# web mercator coordinates
SMR = lonlat_to_web_mercator(lon=(-74.325, -74.270), lat=(40.775, 40.725))
x, y = lonlat_to_web_mercator(lon=list(station_obs["lon"]), lat=list(station_obs["lat"]))
station_obs["x"] = x
station_obs["y"] = y
SMR

In [ ]:
source = ColumnDataSource(
    data = dict(
        lat=list(station_obs['lat']),
        lon=list(station_obs['lon']),
        x=list(station_obs['x']),
        y=list(station_obs['y']),
        name=list(station_obs['name']),
        count=list(station_obs['observations']),
        species=list(station_obs['species']),
        size=[10 + 7*math.log(v + 1) for v in station_obs['observations']],
    )
)

hover = HoverTool(tooltips=[
    ("site", "@name"),
    ("observations", "@count"),
    ("species", "@species")
])

p = figure(title="South Mountain Reservation",
           tools=[hover, WheelZoomTool(), PanTool(), ResetTool()], 
           x_range=SMR[0], y_range=SMR[1], 
           x_axis_type="mercator", y_axis_type="mercator")
p.add_tile(get_provider(OSM))

In [ ]:
p.circle(x="x", y="y", size="size", fill_color="violet", fill_alpha=0.8, source=source)
show(p)